### ISSUE TITLE
Configure /proc/xenomai/latency at run-time from init script

### ISSUE THREAD

**Issue by koppi** [zultron/xenomai-deb#1]
Hi @zultron , just saw your issue: https://github.com/ShabbyX/RTAI/issues/25

Is there a similar mechanism for Xenomai? – I came up with an init script to set `/proc/xenomai/latency` during boot, see:

https://github.com/koppi/mk/blob/master/Machinekit-Xenomai-Thinkpad-X200.md#konfiguration-xenomai

Is there another / better solution for this, I'm not aware of?

**Comment by zultron** [comment]
Hi @koppi,

I was unaware of `/proc/xenomai/latency`.  Does the procedure in [this very old email](https://mail.gna.org/public/xenomai-help/2007-05/msg00035.html) still look correct?

Yes, this can absolutely be done for Xenomai.  There's already an `/etc/init.d/xenomai` script that sets the non-root Xenomai group ID.  You could merge your `xenomai-latency` init script with it.

Instead of setting `LATENCY` in the script, create a simple `/etc/default/xenomai` script:

```
# Minimum positive latency as measured from 'cyclictest'; defaults to 0
#XENOMAI_LATENCY=0
```

In the init script:

```
XENOMAI_LATENCY=0
. /etc/default/xenomai
```

That way, the user may set latency in an `/etc/default` file without altering the `/etc/init.d` script, which conventionally shouldn't be done (so e.g. package upgrades can update the script without clobbering configuration changes).

**Comment by koppi** [comment]
The description of the procedure in the old mail is a bit vague. I'm doing it as follows:

``` bash
$ sudo sh -c 'echo 0 > /proc/xenomai/latency'
$ timeout 6000 xeno latency
```

Next, read the output of "lat min" and calculate LATENCY=abs("lat min" \* 1000).

I cannot merge my init script with `/etc/init.d/xenomai` as `/etc/init.d/xenomai` is part of `libxenomai1`:

``` bash
$ apt-file search /etc/init.d/xenomai
libxenomai1: /etc/init.d/xenomai
```

Can this be somehow handled inside the debian package mechanism? – Any ideas?

**Comment by zultron** [comment]
Sorry, I meant merge your work in `/etc/init.d/xenomai-latency` into `/etc/init.d/xenomai`; not a `git merge`.

When you're done, you can offer it to the Xenomai folks, and I'll certainly be happy to add it as a patch to my Xenomai packages until it's accepted upstream.

**Comment by koppi** [comment]
I'm not an expert with debian packaging voodo, don't know howto do this, sorry. I came across your recent activity on the xenomai mailinglist while researching this issue..

**Comment by zultron** [comment]
That's ok.  If you get this to work and put the files somewhere, I'll turn them into a patch for the Xenomai packages.

**Comment by koppi** [comment]
won't fix.
